#!/usr/bin/env bash
# Multi-repo sessions: generate the workspace-level project layer.
#
# When the portal clones more than one repo, claude runs with cwd = ~/workspace, and Claude
# Code only discovers CLAUDE.md, .claude/skills, .claude/commands, .claude/settings.json and
# hooks from the cwd and its ANCESTORS — never from subdirectories, and `--add-dir` loads none
# of them (docs: cli-reference "additional directories"). So with two repos, neither repo's
# skills, instructions, hooks or permission rules were active. This script fixes that by
# generating, at the workspace root:
#
#   CLAUDE.md                 imports every repo's CLAUDE.md (@<repo>/CLAUDE.md; relative
#                             imports inside those files resolve relative to the importing file)
#   .claude/skills/<name>     symlink -> <repo>/.claude/skills/<name>   (clash: <repo>--<name>)
#   .claude/commands/<name>   symlink -> <repo>/.claude/commands/<name>  (idem)
#   .claude/agents/<name>     symlink -> <repo>/.claude/agents/<name>    (idem)
#   .claude/rules/<name>      symlink -> <repo>/.claude/rules/<name>     (idem)
#   .claude/settings.json     merge of every repo's .claude/settings.json:
#                             permissions.allow/deny/ask/additionalDirectories concatenated,
#                             file-tool rules (Read/Edit/Write/…) rewritten from repo-relative
#                             to //absolute so they keep their original scope, hooks per event
#                             concatenated and statusLine taken from the first repo that has
#                             one — with $CLAUDE_PROJECT_DIR in commands replaced by the repo's
#                             absolute path (Claude Code would set it to the workspace root).
#                             Other scalar keys: first repo (SESSION_REPOS order) wins.
#
# The whole layer is regenerated on every boot (the workspace root is portal-managed; nothing
# hand-written lives there). Idempotent. Usage: workspace-layer.sh [~/workspace]
set -euo pipefail
WS="${1:-$HOME/workspace}"

# Repo order = SESSION_REPOS order (first selected repo wins conflicts), then any others sorted.
declare -a REPOS=()
if [ -n "${SESSION_REPOS:-}" ]; then
  IFS=',' read -ra urls <<< "$SESSION_REPOS"
  for u in "${urls[@]}"; do
    n="$(basename "$(echo "$u" | xargs)" .git)"
    [ -d "$WS/$n" ] && REPOS+=("$n")
  done
fi
while IFS= read -r d; do
  n="$(basename "$d")"
  skip=0; for r in "${REPOS[@]:-}"; do [ "$r" = "$n" ] && skip=1; done
  [ "$skip" = 1 ] || REPOS+=("$n")
done < <(find "$WS" -mindepth 1 -maxdepth 1 -type d -not -name '.*' | sort)

if [ "${#REPOS[@]}" -lt 2 ]; then
  echo "[workspace-layer] ${#REPOS[@]} repo(s) under $WS; nothing to generate"
  exit 0
fi
echo "[workspace-layer] repos: ${REPOS[*]}"

rm -rf "$WS/.claude" "$WS/CLAUDE.md"
mkdir -p "$WS/.claude"

# --- CLAUDE.md: import every repo's instructions ------------------------------
{
  echo "# Multi-repo session (generated by workspace-layer.sh — do not edit)"
  echo
  echo "This session's working directory holds several repos side by side:"
  for r in "${REPOS[@]}"; do echo "- \`$r/\`"; done
  echo
  echo "Each repo's own instructions are imported below and apply to work inside that repo."
  echo "Run git commands inside the repo directories, not here. Skills, hooks and permission"
  echo "rules from every repo are active (see \`.claude/\` here, which links to the repos' own)."
  echo
  for r in "${REPOS[@]}"; do
    [ -f "$WS/$r/CLAUDE.md" ] && { echo "## $r"; echo; echo "@$r/CLAUDE.md"; echo; }
  done
} > "$WS/CLAUDE.md"

# --- skills / commands / agents / rules: symlinks ------------------------------
link_dir() {  # link_dir <kind>   (children of <repo>/.claude/<kind>/ -> <ws>/.claude/<kind>/)
  local kind="$1" r src dst name n=0
  for r in "${REPOS[@]}"; do
    src="$WS/$r/.claude/$kind"; [ -d "$src" ] || continue
    mkdir -p "$WS/.claude/$kind"
    for p in "$src"/*; do
      [ -e "$p" ] || continue
      name="$(basename "$p")"; dst="$WS/.claude/$kind/$name"
      [ -e "$dst" ] && dst="$WS/.claude/$kind/$r--$name"
      ln -s "$p" "$dst"; n=$((n+1))
    done
  done
  [ "$n" -gt 0 ] && echo "[workspace-layer] $kind: $n linked"
  return 0
}
link_dir skills; link_dir commands; link_dir agents; link_dir rules

# --- settings.json: merge ---------------------------------------------------------
python3 - "$WS" "${REPOS[@]}" <<'PY'
import json, os, re, sys
ws, repos = sys.argv[1], sys.argv[2:]
FILE_TOOLS = ("Read", "Edit", "Write", "MultiEdit", "NotebookEdit")

def scope_rule(rule, root):
    """Re-anchor a repo-relative file-tool rule to the repo's absolute path."""
    m = re.fullmatch(r"(\w+)\((.*)\)", rule)
    if not m or m.group(1) not in FILE_TOOLS:
        return rule
    tool, pat = m.groups()
    if pat.startswith("//") or pat.startswith("~"):
        return rule                         # already absolute / home-relative
    if pat.startswith("/"):
        return f"{tool}(//{root.lstrip('/')}{pat})"   # project-root relative
    return f"{tool}(//{root.lstrip('/')}/{pat})"      # cwd relative

def subst(obj, root):
    if isinstance(obj, str):
        return obj.replace("${CLAUDE_PROJECT_DIR}", root).replace("$CLAUDE_PROJECT_DIR", root)
    if isinstance(obj, list):
        return [subst(x, root) for x in obj]
    if isinstance(obj, dict):
        return {k: subst(v, root) for k, v in obj.items()}
    return obj

merged, notes = {}, []
for r in repos:
    root = os.path.join(ws, r)
    p = os.path.join(root, ".claude", "settings.json")
    if not os.path.isfile(p):
        continue
    try:
        s = json.load(open(p))
    except Exception as e:
        notes.append(f"{r}: settings.json unreadable ({e}); skipped"); continue
    for k, v in s.items():
        if k == "permissions":
            mp = merged.setdefault("permissions", {})
            for lk in ("allow", "deny", "ask"):
                for rule in v.get(lk, []) or []:
                    rule = scope_rule(rule, root)
                    if rule not in mp.setdefault(lk, []):
                        mp[lk].append(rule)
            for d in v.get("additionalDirectories", []) or []:
                d2 = d if os.path.isabs(os.path.expanduser(d)) else os.path.join(root, d)
                if d2 not in mp.setdefault("additionalDirectories", []):
                    mp["additionalDirectories"].append(d2)
            for pk, pv in v.items():
                if pk not in ("allow", "deny", "ask", "additionalDirectories"):
                    if pk in mp and mp[pk] != pv: notes.append(f"{r}: permissions.{pk} conflicts; keeping earlier")
                    else: mp.setdefault(pk, pv)
        elif k == "hooks":
            mh = merged.setdefault("hooks", {})
            for ev, groups in (v or {}).items():
                mh.setdefault(ev, []).extend(subst(groups, root))
        elif k == "env":
            me = merged.setdefault("env", {})
            for ek, ev in (v or {}).items():
                if ek in me and me[ek] != ev: notes.append(f"{r}: env.{ek} conflicts; keeping earlier")
                else: me.setdefault(ek, ev)
        else:
            if k in merged and merged[k] != v:
                notes.append(f"{r}: {k} conflicts; keeping earlier")
            else:
                merged.setdefault(k, subst(v, root))

# a settings.local.json at the workspace root would be lost on regenerate; none is expected.
out = os.path.join(ws, ".claude", "settings.json")
json.dump(merged, open(out, "w"), indent=2)
print(f"[workspace-layer] settings.json: {len(merged.get('permissions',{}).get('allow',[]))} allow, "
      f"{len(merged.get('permissions',{}).get('deny',[]))} deny, "
      f"{sum(len(g) for g in merged.get('hooks',{}).values())} hook group(s)")
for n in notes: print("[workspace-layer] note:", n)
PY
echo "[workspace-layer] done"
