{
  "apiVersion": "v1",
  "kind": "ConfigMap",
  "metadata": {
    "name": "portal-config",
    "namespace": "claude"
  },
  "data": {
    "repos.json": "[{\"name\":\"claude-env\",\"url\":\"https://github.com/de0ch/claude-env.git\"},{\"name\":\"chian-train\",\"url\":\"github.com/chian-train\"}]",
    "sessionImage": "registry.fly.io/de0ch-claude-sessions:deployment-01M2CVGP5ZM64DGXPK2G8DD8PV"
  }
}
