apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: portal-secrets
    namespace: claude
stringData:
    FLY_API_TOKEN: ENC[AES256_GCM,data:sl9TBKeYl/ngSbV6Aq97EyKNEKSepV8wWZ1iZAjgUVEUciMDXfsM6C6DNO2MnDQTXcOTDD7SzkJcyJ/2G6cXNXWA11wKkhWts22qnI9tVlP/NPu0rSdQMQVP/nYVkWlHXLKCJ3qFddT+KBkZAw4wzHBBtOazTrds/Uma3xm0L94edLVBGPmFMCCW+OQOOD7MTGEcghQiCzRU4XK6BuXVjuxQNTSkQVEBNc32IO8lEwyoB2+/VgDNMjlHTIxERe/EOTLcXwD/h7eWotc7RKFKoycpLKKAJ45lJejXrwccq9K+lHxYG2oRPDUWb17iKQa178wz55lI5Irhe68ZYRnDwN2WnkxhfmdfoiQ24FYX7rn/Edt2wBloBrEay8rTqWZHg5m2qSuYKlKFWd6xLBkgvBS2gbXgZHF6HaXxG3O1OguH+vMelc8C336exjF6GSDB/diNtSKyoj+XHJOImY7N9Exizv1wXU1ha5WbP7h98esv1PwmOAO1iG/707QkJrMkorH3wSVKk86Ba9jlOytx6OGYwPEo3oShJrfyDUhk95uvwce1ETwZRgmc55c2+on8PrHqtPxjdDBT53kkIVVWGTdlB4SZuQZDx9awP5xreX7njQ6sedL2KmOghlUOsD3R5CoFsNZBPd48ccaHAxxDa+6YJoHBVxxNmvn5XCw3iC3AUHA+gfsd65Im+LTRGZdrdyjkE6eueJ6LHyJd4WRIWCP69/B4UGY6xey8c7Eo3pcfVOFJ2OaNwpehgggQJ7T8eIiYn7LiHkvn9auwL0UggztoBuwO9B4rbstVjX7qzagQzepdfaqjZCngRlpzLUFxTMoOXks73pbWjZNK37egi0eLeTQppEU=,iv:h9SSKf9t0wPqPFBxe3HuUqPnz00nVti6qmeNFpEQPqM=,tag:7GqyHWJ6gFcZV2UtpYoXYA==,type:str]
    CF_ACCESS_CLIENT_ID: ENC[AES256_GCM,data:EQfxCyCNSxjVBB8uu5eIjYTry6E9vAcmJsEv4WyFZEpNjaiWQryN,iv:zoUVCkfBF3xI/tLkNlNZn/JowxqKin4eAhDJQlWewNs=,tag:WvZkPzy4iNW303aig3SsKg==,type:str]
    CF_ACCESS_CLIENT_SECRET: ENC[AES256_GCM,data:L/GPd1IaMKd4kbyaCFc+mwyyZOsYlXXzuAdQ71wPon7rw3zNdtNz5ZjGjaeyUrhfWIErRmISlZGukMp/vphPtg==,iv:Uc5NMc18xYxqWDTm2QnFy8yO/99JpOQIY/IvAKAVc0I=,tag:dMAGFokqNFNd7tMq7Dl9Ew==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:CsbQyOgT/8fcz4K9K1a7E8zXmVvSu5mIho0cfwyxIusV0aS8RU7OJg==,iv:lj+495CjgtgjFUuD3ZrrAHhgiAjVjTcWl5zy5bMMgLc=,tag:q7W30q3tgKjPqiBpr1L4Hg==,type:str]
sops:
    age:
        - recipient: age1q94us00rr2edy94fk826lhspyndr73rhr6tn53hyk750md6gx9cqls9tr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UW9mQ2RvZkowdXZKbFVT
            Q3FGTHRlTTV0Z3FSY3J3Qjh5QjkvVzhUZVUwCnR6ZVFkY3lMR3l1elBxWDFudXdv
            K0pJcnFFWWh4L3JWUDBidkRzSWFPVjgKLS0tIERtZHdhL1ZsazJKKzFtUkhHYVI3
            VzZ2cS9SdUZrSGFNRlZxVytycGlvYkkKaBPmhi823FBfbc9cE/pVa4IJaUTkINsB
            +Ubhv94MUS9S/wQODS/XlfgbD+WIM4HzL0LJ3toQfuRXfVSVUgGHaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T05:50:44Z"
    mac: ENC[AES256_GCM,data:Q0Tp1bNRmaCfXxpF4OFKTTIYyaBe3wjB9swcTqd5WLpV/cBq4acTy+u2kMP8Kt7J4WlcuknZFfmf9KLFSOk6D7aK9TflUPVdosPASSm3hQUbkRKPmVmqOhaRp7zstR63hQTpjD/Xpv+VtLc5iLTwBQH+coyxH6dftUQCgAxLZzg=,iv:m+YQ1jleCO/8r8L9HLIflo0yPz0aF3UKBWhloRmtVkA=,tag:HcgwDcDCzZExFABKMbALXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
