apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: portal-secrets
    namespace: claude
stringData:
    CF_ACCESS_CLIENT_ID: ENC[AES256_GCM,data:H5vdvndNHn6l6kbSmxOMdfTpVM7cvHlUUMbD5Fk7ZrdDr3k/roRH,iv:DaPfatBYPuKATX+tOATR+HGl9U46z7asDwa2eRllmM4=,tag:HsfWho2o9Nl019y85TsrlQ==,type:str]
    CF_ACCESS_CLIENT_SECRET: ENC[AES256_GCM,data:HPILZg7ZUTU/GF3r+4zXJT62jJ7ony7jTiLlHsMoXTwlQA/eDy/ijYpN5n85nD3r2owDa6NK1OprRzBkQ9tzCA==,iv:QemDiZJfAirU5YVrdwZE+b8gUgsGu12HtvYa2FV82/g=,tag:zpPLcaqCDv6fNvoQXRgRgg==,type:str]
    FLY_API_TOKEN: ENC[AES256_GCM,data:wnfBydmsjN3IyUVIxPwHtbkaS6Djm6UtkaJInHOEKZbJpyYkot2xvSh2FaPMs86qHtWwJB7oe+6LC2s/FKhMXIFYoTNoD/1bdr6sLqlUR0Ck/V5UopdUcriq0j0eDCS9AMJFWJUuGs0qF9r6okpFYIsTmJxuxQihsq9k6JYX6JLoSSpu8NhCguYvnjj7QD4SF2arQB8GpxAA9IV8j2T288PrL4sxHb3ykfRWoFPO1/lZyKw1zi7Sax8yO5TbbLlVbD/txwh2agZX5IHA0tjuLDFqm/rUocaWsBZ8v2Ysz2OoNmOi1V3k1VyjdtlIoBVgLjtC22pnR6JOD1t0ikm3wv8Xy7Ic1YVrfHps2p9mApsZrvgorPnv3+rT0mcJ827KzvKj251r2zVChJPL+ZjgOy6eDCod58TeLGXPvvujAopvn+d3zFXPkGXPWmmQ8iDUGDXbWnto0pTGI/haLg+XsplVkS8u5PSOPnNGiSXqx+nU1JhvmyreYiaPE9hDCYDwTO+U68sM7WlfCixxbg0lXLyA/45DsrNQqN/dB5WQAKrUIucTU6tFbr8YNC4mP7lBHIBI82FKrdFkRQ8AlKAwhCB2jJtd8ekW9q5AtE1Yp3B5+n+DYR1Gy829fxCnec5ZsiJxBSKdlL0yyxXN2090ftmokCTRvabbncxyEfbiBi2LbfW8f0UjoRbnq0ClEGUeNvi49WZQ6u6dwewiTJlXDwRScl8+PopmD2HmruOmJZhLXBPduxOjCqHZwqsgxkOeWsSfylI80uvj9Uw9SxaTfDoIzxqTzmAL6HK17yPcXexKm9HQpmveD7iznyixwphglS9HREdheao9fhfkmRvQ2ZFr2Sp1gqhl3brb,iv:SEt/P1iWGhuM9JajzHgRpByr6QBMHH0XKQdYBNfHmS4=,tag:LrcZ/NUJ5ynZvIdL+dwlUg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:foUu+EBMX9Cz5LkKudXLMON3Eo/N/cJFfLEYuYInjOGwaSlTbUK8Xg==,iv:XWAsrxrHoFoegsZsb/GgFor0ap2YjehfxuQIZeyIzu8=,tag:kn9DDp2NIGgJ3CFM9kKYzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbFBOVFdHZzMrclNwand4
            LzJsQUNpMmU0Q0s4b2ZPNmR5T3JybGc1MTFBCjFJVXgvVjBjbGxOdlRDSk5DdS9F
            MnROWk9hMnZScGU1aXlrN3FIR3YweUkKLS0tIEhTSVg5cFFMMmJjRVRNakFwSmd1
            TkhHY1ZKT3BXR1grS2s1WGJMRVBEMU0KFUMMtwK/fcHGh0RuKwcRpBvqBQBAy+KK
            f+a/58RrHnbroHUjp+/tBm4Q3rpxyRTxAgV7PcDhne0CJ6yzeUxteg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q94us00rr2edy94fk826lhspyndr73rhr6tn53hyk750md6gx9cqls9tr3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T07:57:27Z"
    mac: ENC[AES256_GCM,data:udDq61F/z6D+jUMMgsWoo58vIS6oaBAQfoVqTYPDdr0/wzPCLQr6GkD/8HkF1v8S81CMN+ap+frYt9mdt1p0ksE97Dn3Lmcxl/o1MuanJF5sndYv2rXLpmXnXO0Y6Rb4E1aZg/KNcbJpV+a1niWUifYtAX5Ovk1dAN4BH4snBjg=,iv:VbLzLQ84o1dBMq+oTMBvUkJJ4eNyo4AiL60rLsvY5Ms=,tag:PT1XiRKiNFoac6ckMtylkg==,type:str]
    version: 3.13.3
