// Write-through to git: every dashboard edit is committed to the repo (Secrets encrypted with
// sops for the cluster's age key, config as plain YAML) BEFORE it's applied to the cluster —
// git is the source of truth and Flux would overwrite anything that isn't in it.
// Keeps a shallow clone in $HOME/repo; all transactions are serialised.
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFile } = require("child_process");

const REPO_URL = process.env.REPO_URL || "https://github.com/DE0CH/claude-env.git";
const BRANCH = process.env.REPO_BRANCH || "main";
const DIR = process.env.REPO_DIR || path.join(os.homedir(), "repo");
const K8S_DIR = "selfhost/k8s";
const SECRETS_DIR = `${K8S_DIR}/secrets`;

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    execFile(cmd, args, { cwd: DIR, maxBuffer: 8 * 1024 * 1024, ...opts }, (err, stdout, stderr) => {
      if (err) { err.message = `${cmd} ${args.join(" ")}: ${String(stderr || err.message).slice(0, 500)}`; return reject(err); }
      resolve(String(stdout));
    });
  });
}
const git = (...args) => run("git", args);
function authUrl() {
  const t = process.env.GITHUB_TOKEN;
  if (!t) throw new Error("GITHUB_TOKEN missing — the portal can't commit to git");
  return REPO_URL.replace(/^https:\/\//, `https://x-access-token:${t}@`);
}

async function ensure() {
  if (!fs.existsSync(path.join(DIR, ".git"))) {
    fs.mkdirSync(path.dirname(DIR), { recursive: true });
    await run("git", ["clone", "--depth", "1", "-b", BRANCH, authUrl(), DIR], { cwd: os.homedir() });
    await git("config", "user.name", "claude-portal");
    await git("config", "user.email", "portal@selfhost.claude");
  }
  await git("remote", "set-url", "origin", authUrl());
  await git("fetch", "--depth", "1", "origin", BRANCH);
  await git("reset", "--hard", `origin/${BRANCH}`);
  await git("clean", "-fdq", K8S_DIR);
}

let chain = Promise.resolve();
// fn(repoDir) writes files; returns nothing. Retries the whole thing on push races.
function transaction(message, fn) {
  const p = chain.then(async () => {
    let lastErr;
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        await ensure();
        await fn(DIR);
        regenerateSecretsKustomization();
        await git("add", "-A", K8S_DIR);
        const status = await git("status", "--porcelain", "--", K8S_DIR);
        if (!status.trim()) return { committed: false };
        await git("commit", "-q", "-m", `${message} [skip ci]`);
        await git("push", "-q", "origin", `HEAD:${BRANCH}`);
        return { committed: true };
      } catch (e) { lastErr = e; await new Promise((r) => setTimeout(r, 1500 * (attempt + 1))); }
    }
    throw lastErr;
  });
  chain = p.catch(() => {});
  return p;
}

// Secret manifests are written as JSON (valid YAML) then encrypted in place; the .sops.yaml
// creation rule matches by path, so the file must already be at its final location.
async function writeEncryptedSecret(relPath, manifest) {
  const abs = path.join(DIR, relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, JSON.stringify(manifest, null, 2) + "\n", { mode: 0o600 });
  await run("sops", ["--encrypt", "--in-place", relPath]);
}
function writeYamlish(relPath, obj) {
  const abs = path.join(DIR, relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, JSON.stringify(obj, null, 2) + "\n");
}
function removeFile(relPath) { try { fs.unlinkSync(path.join(DIR, relPath)); } catch {} }
function regenerateSecretsKustomization() {
  const dir = path.join(DIR, SECRETS_DIR);
  fs.mkdirSync(dir, { recursive: true });
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".sops.yaml")).sort();
  const body = "# GENERATED by the portal (lib/gitsync.js) — lists every *.sops.yaml in this directory.\n"
    + "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:"
    + (files.length ? "\n" + files.map((f) => `  - ${f}`).join("\n") : " []") + "\n";
  fs.writeFileSync(path.join(dir, "kustomization.yaml"), body);
}

module.exports = { transaction, writeEncryptedSecret, writeYamlish, removeFile, DIR, SECRETS_DIR, K8S_DIR, ensure };
